<?php

/**
 * Abstract class to define/implement base methods for all controller classes
 *
 * @since      1.0.0
 * @package    Plugin_Name
 * @subpackage Plugin_Name/controllers
 */

if ( ! class_exists( 'Plugin_Name_Controller' ) ) {
	abstract class Plugin_Name_Controller {

		protected $model;

		/**
		 * Provides access to a single instance of a module using the singleton pattern
		 *
		 * @return object
		 *
		 * @since    1.0.0
		 */
		public static function get_instance( $model_class_name = false, $view_class_name = false ) {
			$classname = get_called_class();
			$key_in_registry = Plugin_Name_Controller_Registry::get_key( $classname, $model_class_name, $view_class_name );

			$instance = Plugin_Name_Controller_Registry::get( $key_in_registry );

			if ( $instance === null ) {
				$instance = new $classname( $model_class_name, $view_class_name );
				Plugin_Name_Controller_Registry::set( $key_in_registry, $instance );
			}

			return $instance;
		}

		/**
		 * Get model
		 *
		 * @return object
		 *
		 * @since    1.0.0
		 */
		protected function get_model() {
			return $this->model;
		}

		/**
		 * Get view
		 *
		 * @return object
		 *
		 * @since    1.0.0
		 */
		protected function get_view() {
			return $this->view;
		}

		/**
		 * Clears caches of content generated by caching plugins like WP Super Cache
		 *
		 * @since    1.0.0
		 */
		protected static function clear_caching_plugins() {

			// WP Super Cache
			if ( function_exists( 'wp_cache_clear_cache' ) ) {
				wp_cache_clear_cache();
			}

			// W3 Total Cache
			if ( class_exists( 'W3_Plugin_TotalCacheAdmin' ) ) {
				$w3_total_cache = w3_instance( 'W3_Plugin_TotalCacheAdmin' );
				if ( method_exists( $w3_total_cache, 'flush_all' ) ) {
					$w3_total_cache->flush_all();
				}
			}
		}

		/**
		 * Constructor
		 */
		protected function __construct( $model_class_name = false, $view_class_name = false ) {
			if ( $model_class_name != false ) {
				$this->model = $model_class_name::get_instance();
			}

			if ( $view_class_name != false ) {
				$this->view = new $view_class_name;
			}
		}

		/**
		 * Register callbacks for actions and filters
		 */
		abstract protected function register_hook_callbacks();

	}

}
